FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
EXPOSE 8000
CMD ["npm", "start"]
# This Dockerfile sets up a Node.js environment using the official Node.js 24 Alpine image.