name: LMS containerization CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username:  ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name : Genrate docker image tags
        run: echo "IMAGE_TAG=$GITHUB_SHA--$(DATE +%Y%m%d%H%M%S)--$GITHUB_RUN_ATTEMPT" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: build frontend
        run : docker build ./frontend -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:$IMAGE_TAG
      - name: build backend
        run : docker build ./backend -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:$IMAGE_TAG  
      - name: Push to Docker
        run: |
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/frontend
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/backend

  Run-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME}}
          password: ${{ secrets.PASSWORD}}
          script: |
            cd /home/eshiet/lms
            ./deploy.sh