name: LMS containerization CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username:  ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: build Frontend
        run : docker build ./frontend -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:0.1
      - name: build Backend
        run : docker build ./backend -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:0.1
      - name: Push to Docker
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:0.1
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:0.1
        
