name: LMS containerization CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        id: login
        uses: docker/login-action@v3.4.0
        with:
          username:  ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: check login failure
        id: check_login
        if: ${{always()}}
        run: |
          if [[ "${{steps.login.conclusion}}" == 'falure' ]]; then
            echo "Error_message=Docker login failure" >> $$GITHUB_ENV
            echo "Failed_job=Build" >> $$GITHUB_ENV
          fi
      - name : Genrate docker image tags
        run: echo "IMAGE_TAG=$GITHUB_SHA--$(date +%Y%m%d%H%M%S)--$GITHUB_RUN_ATTEMPT" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: build frontend
        id: build_frontend
        run : |
        
          docker build ./frontend -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:$IMAGE_TAG 2>&1 | tee output.txt

          if [ $step_exit_code == 1 ]; then
            cat output.txt
          fi

          echo "The Exit code is: $step_exit_code"

      - name: check frontend build
        id: _if_frontend_failed
        if: ${{always()}}
        run: |
          if [[ "${{ steps.build_frontend.conclusion }}" == "failure" ]]; then
            echo "Error_message=something went wrong" >> $GITHUB_ENV
            echo "Failed_job=Build" >> $GITHUB_ENV
          fi
      - name: build backend
        run : docker build ./backend -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:$IMAGE_TAG  
      - name: Push to Docker
        run: |
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/frontend
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/backend
      - name: Build and push LMS image
        if: ${{failure()}}
        run: |
           echo "The workflow started by ${{github.actor}} has failed see details >>> Job: $Failed_job, Error Message: $Message_log"

  Run-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        id: deploy_to_linux
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST}}
          username: ${{ secrets.USERNAME}}
          password: ${{ secrets.PASSWORD}}
          script: |
            cd /home/eshiet/lms
            ./deploy.sh

      - name: check deploy failure
        if: ${{always()}}
        run: |
          if [[ "${{ steps.deploy_to_linux.conclusion }}" == "failure" ]]; then
            echo "Error_message=Can not login to remote machine ${{ secrets.HOST }}" >> $GITHUB_ENV
            echo "Failed_job=Run-deploy" >> $GITHUB_ENV
          fi
      - name: Run on failure
        if: ${{failure()}}
        run: |
          echo "The workflow started by ${{github.actor}} has failed see details >>> Job: $Failed_job, Error Message: $Error_message"
